import type { ReviewItem } from "../types/ReviewItem";

export const reviewQueue: ReviewItem[] = [
  {
    id: "DOC-2041",
    title: "Q2 Board Deck",
    owner: "Mara Liu",
    stage: "Executive",
    department: "Strategy",
    due: "today • 6:00 PM",
    priority: "High",
    updated: "15m ago",
  },
  {
    id: "DOC-1988",
    title: "Vendor MSA — Northwind",
    owner: "Gabriel Mendez",
    stage: "Legal",
    department: "Revenue",
    due: "tomorrow",
    priority: "Medium",
    updated: "1h ago",
  },
  {
    id: "DOC-1877",
    title: "PCI Self-Assessment",
    owner: "Samira Patel",
    stage: "Security",
    department: "GRC",
    due: "in 3 days",
    priority: "High",
    updated: "2h ago",
  },
  {
    id: "DOC-1765",
    title: "FY26 Budget Reforecast",
    owner: "Trevor K",
    stage: "Finance",
    department: "FP&A",
    due: "next week",
    priority: "Low",
    updated: "yesterday",
  },
  {
    id: "DOC-1702",
    title: "Data Processing Addendum",
    owner: "Nia Gomez",
    stage: "Risk",
    department: "Compliance",
    due: "due Friday",
    priority: "Medium",
    updated: "45m ago",
  },
];
